//! # Burn Central Runtime
//!
//! This crate is the middle layer of the Burn Central SDK. It communicate directly with the
//! generate crate created by Burn Central CLI and provide the necessary building block to execute
//! training and inference routines.
//!
//! # Features
//! - Extractor for training and inference arguments.
//! - Wrapper for return type of training and inference routines.
//! - Executor to run training and inference routines.
//! - Error handling for runtime execution.
//!
//! # Hidden element
//! This crate also expose some hidden elements that are only to be used by the code generated by
//! Burn Central CLI. These elements are not meant to be used directly by the end user.

mod error;
mod executor;
mod output;
mod params;
mod routine;
mod telemetry;
mod type_name;

// TODO: document inference module (probably should use the module instead)
#[doc(hidden)]
pub mod inference;

// Hide element that are only used internally by the gen crate.
#[doc(hidden)]
pub mod cli;

pub use error::RuntimeError;
pub use executor::{Executor, ExecutorBuilder};
pub use params::{
    args::{Args, ExperimentArgs},
    artifact_loader::ArtifactLoader,
    default::{Model, MultiDevice},
};
